USE [master]
GO

/****** Object:  Database [RI2]    Script Date: 11/10/2020 1:05:09 PM ******/
CREATE DATABASE [RI2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RI2', FILENAME = N'F:\sqldata\RI2.mdf' , SIZE = 68544KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RI2_log', FILENAME = N'E:\sqllog\RI2.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [RI2] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RI2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RI2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RI2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RI2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RI2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RI2] SET ARITHABORT OFF 
GO

ALTER DATABASE [RI2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RI2] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [RI2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RI2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RI2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RI2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RI2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RI2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RI2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RI2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RI2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RI2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RI2] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [RI2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RI2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RI2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RI2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RI2] SET RECOVERY FULL 
GO

ALTER DATABASE [RI2] SET  MULTI_USER 
GO

ALTER DATABASE [RI2] SET PAGE_VERIFY TORN_PAGE_DETECTION  
GO

ALTER DATABASE [RI2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RI2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RI2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RI2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RI2] SET QUERY_STORE = OFF
GO

USE [RI2]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [RI2] SET  READ_WRITE 
GO

